### ISSUE TITLE
Record Button Not Working in “Clip Launcher” Record Level

### ISSUE THREAD

**Issue by Enkerli** [Jengamon/Launchpad-X-Bitwig-Script#10]
Can’t find a way for the record button to work in Clip Launcher mode.

Expected behaviour: The “Record/Capture MIDI” button should light up while recording a clip. Pressing that button while recording a clip will stop the recording and start playing the clip.

Actual behaviour: This button doesn’t light up during clip recording and pressing it has no impact.

Either it’s a bug with my setup (LPX firmware V1.0.4, Build 351, BWS 3.2.6 on macOS 10.14.6) or there’s something missing from the documentation. Is there a preference somewhere which could affect this? Tried adding a “Toggle Record” controller shortcut but that only works at the global level.

![Screen Shot 2020-08-11 at 08 06 53](https://user-images.githubusercontent.com/327544/89896319-444cdd00-dbab-11ea-8aa5-f85c6f0de677.png)

**Comment by Jengamon** [comment]
Those record button settings make the record button control "Clip Launcher Overdub" rather than any actual Record Button. The Record Button only activates at a global level for the Arranger, so it doesn't really make sense for the clip launcher. To stop the recording and start playing the clip, you just pressed the clip being recorded to.

**Comment by Enkerli** [comment]
Oh… So, if I’m in Note mode, recording a clip, I need to switch back to Session mode to stop the recording? That’s quite a bit of gymnastics! (And very different from the way it works in Live.)
Is this a Bitwig limitation? Is there no way to tell it to stop recording a clip?

**Comment by Jengamon** [comment]
How does it work in Live? I have it working in a simple way, but I do want to reproduce the Live interactions. (I don't have Live, so I don't really know.)

**Comment by Jengamon** [comment]
According to the user manual, this is pretty much how it works in Live (except Capture MIDI, which is not [yet] a thing in Bitwig). 
![image](https://user-images.githubusercontent.com/1479994/91653643-98433700-ea70-11ea-8b0c-299d9210a844.png)

Please get back to me. I will close this issue in about a week.

**Comment by Jengamon** [comment]
Closing...

**Comment by Jengamon** [comment]
Ok, I understand the feature. Let me see if I can implement it.

**Comment by Jengamon** [comment]
Just for posterity's sake: Note that this feature will stop recording, *then* launch the clip, so if you use quantize clip starts, you might wait a little for the clip to start playing again.

**Comment by Jengamon** [comment]
Also, it can only stop clips that would be visible from the session view.

**Comment by Jengamon** [comment]
So now the Toggle Record mode behavior checks for any playing clips (visible within the bank), and if there are, relaunches those, *instead* of toggling recording (if you have the option enabled).
