### ISSUE TITLE
Cannot find LaunchpadX.bwextension in the latest update

### ISSUE THREAD

**Issue by thresholdpeople** [Jengamon/Launchpad-X-Bitwig-Script#17]
sorry! i feel like i'm missing something glaringly obvious.

**Comment by Jengamon** [comment]
Sorry, it should be here now: https://github.com/Jengamon/Launchpad-X-Bitwig-Script/releases/download/v1.1.5/LaunchpadX.bwextension.

It takes a bit of time for Github Actions to test, build, and upload the freshly compiled extension to the release.
