### ISSUE TITLE
Not actually an issue, I'd love to contribute to your framework

### ISSUE THREAD

**Issue by flowstate** [Jengamon/Launchpad-X-Bitwig-Script#6]
I just got here by way of realizing that the JS API doesn't support any of the HardwareSurface stuff I'm trying to do for the Maschine MK3 script I'm writing. 

I'm a professional JS dev, haven't touched Java in a while... since 7, I think. Anyways, I'd love to contribute, just gotta refresh myself on how to set up java in VSCode, and then I was hoping to get some advice from you on how to set up my local dev environment specifically for Bitwig.

If not, no worries, I'll figure it out eventually. Either way, this repo is a great resource, so thanks for putting it up.

~Eric

**Comment by Jengamon** [comment]
I'm *really* lazy, so I just use IDEA, cuz it lets me IDE my way through most things. I'm not really sure on how to get things compiling with VSCode, but I'd assume the javac commandline workflow would work, although a little inconvient. I'm using jdk-13.0.2 if that helps anything.
